### ISSUE TITLE
frequent console.log calls result in 100% cpu and hanging

### ISSUE THREAD

**Issue by vaeroon** [airportyh/testem#212]
I am not sure whats happening here. I wanted to test out the performance of testem (when running the tests in phantomjs in dev mode). I added a couple of for-loops to see the effect. Here is the test that I am trying to execute:
```javascript
describe('hello', function(){
    it('should say hello', function(){
        for(var i=0; i<100; i++){
          for(var j=0; j<100; j++){
            console.log("hello ", i, " ", j, " ", (i*j));
          }
        }
        expect(hello()).toBe('hello world');
    });
    
    it('should say hello to person', function(){
        for(var i=0; i<100; i++){
          for(var j=0; j<100; j++){
            console.log("hello ", i, " ", j, " ", (i*j));
          }
        }
        expect(hello('Bob')).toBe('hello Bob');
    });
});
```
I tried this multiple times. The consistent result is that the process (testem) hangs. I have a 2-core cpu. One of the cores gets continously maxed-out at 100%. The system monitor clearly shows the NodeJS process to be consuming the cpu. PhantomJS also seems to be consuming significant memory (a few hundreds of Megs). Eventually I have to manually kill both the processes (NodeJS, PhantomJS).

I am really not sure whats going on here. To compare I took the same for-loops and executed them directly under NodeJS. It runs in under a couple of secs without even a blip to cpu/memory.

**Comment by johanneswuerbach** [comment]
The issue should be fixed by: https://github.com/airportyh/testem/pull/453

**Comment by jreading** [comment]
FWIW, I am having this problem. We have tons of deprecation warnings in one app and about 80 tests. Everything eventually grinds to a halt.

**Comment by johanneswuerbach** [comment]
Mind creating a new issue with more details (browser, node version, etc.)?
