### ISSUE TITLE
Ctrl+C does not kill launchers

### ISSUE THREAD

**Issue by iUtvikler** [airportyh/testem#334]
Next time I run testem I get multiple instances of each launcher (like 2 PhantomJS tabs)
Seems like this callback is never called: (SIGINT)
https://github.com/airportyh/testem/blob/master/lib/dev/index.js#L129

**Comment by CodeOfficer** [comment]
So this is definitely still an issue for me given the exact steps outlined above by @iUtvikler.

Using 0.7.1. Am I missing something?

**Comment by stefanpenner** [comment]
> Using testem 0.7.1 and node 0.10.31. Am I missing something?

also still seeing this.
