### ISSUE TITLE
No tests for 'testem ci'

### ISSUE THREAD

**Issue by Shridhad** [airportyh/testem#371]
I am using `testem-0.6.16`. It is working fine for me when I run my tests in dev mode with `testem` command, but when I run `testem ci` command it is not able to find any tests.  My tests are all jasmine tests and I run them on PhantomJS. 

Following is output that I get when I run `testem ci` -
 
![screen shot 2014-06-06 at 8 20 55 pm](https://cloud.githubusercontent.com/assets/1949852/3201662/03dc5900-ed8a-11e3-84b7-4882fe01506d.png)

But When I run just `testem`, it works fine - 

![screen shot 2014-06-06 at 8 22 29 pm](https://cloud.githubusercontent.com/assets/1949852/3201678/3a994430-ed8a-11e3-8fa3-4b23ca57738f.png)

Here is my testem.yml file-

```
test_page: "jasmine/SpecRunner.html"
launch_in_dev: [PhantomJS]
launch_in_ci: [PhantomJS]
phantomjs_debug_port: 21000
```

I am not able to find out what is wrong here.

**Comment by einoodle** [comment]
I've got the same problem. When running in dev mode, a lot of tests is reported back from browser (tested with both chrome and safari), but in CI mode it never reports back.
I've checked that testem.js indeed emit's the messages from the browser, but the never seem to hit testem.

Further investigations shown that closing the browser reports back one test run, with multiple different browsers it returns one test run per browser.
I've tried both with requirejs and without but same result.
Also tested with both nodejs 0.10.33 and 0.11.14.
All test run with OS X Yosemite.

**Comment by einoodle** [comment]
I've found out that the issue with my setup. I had a redirect (made with a meta refresh) on the test_page which clearly lead to the issue. I've removed the redirect and now my setup works as it should. Anybody else still having the issue?

**Comment by Vytalyi** [comment]
Was this issue resolved? I have same thing - working tests in dev mode, and 0 in ci mode.
