### ISSUE TITLE
Slow static file serving on Ubuntu during Testem run. 

### ISSUE THREAD

**Issue by kevindente** [airportyh/testem#376]
We're using Testem to serve a bunch of HTML files (templates). Under the covers Testem uses the "res.sendfile" method of Express to send the static file back to the client. On Mac machines this is very fast - 1-2 ms per file according to the Chrome network trace. On an Ubuntu machine, however, it takes 39ms. 

Anyone else seeing this, or have suggestions on how to diagnose?

**Comment by johanneswuerbach** [comment]
I think this should be reported to the express issue tracker. We updated recently to express 4, so your issue might be already resolved.
