### ISSUE TITLE
Not all tests are executed in ci mode

### ISSUE THREAD

**Issue by EvgeniyTatarin** [airportyh/testem#388]
Hello,

I have a main file which is invoked by testem, main file refers to several files with tests (eg test1.js, test2.js, test3.js). If I run testem in "dev" mode - all tests from all files are executed. If I do the same in the "ci" mode mostly only tests from the first file are executed. Sometimes tests from another test files are executed as well (mostly in FF); sometimes tests aren't executed at all in IE (i run them in IE,FF,Chrome). But I can see that IE browser was opened, however no result from it were provided.
I haven't found any solution for this issue or already created topic.

Thanks in advance,
Evgeniy

**Comment by johanneswuerbach** [comment]
Do you have a repo, where I can reproduce this issue?
