### ISSUE TITLE
Testem uses an old version of Chai

### ISSUE THREAD

**Issue by unwiredbrain** [airportyh/testem#399]
The latest stable Chai version is 1.9.1 but the one shipped with Testem is version 1.5.0, which is missing some goodies like `.members()`, among others.

Can you please update? Is there a rationale behind shipping Testem with such an old version of Chai?

At the moment I have to resort back to "plain" `mocha` as framework (instead of `mocha+chai`) and serving Chai from the `node_modules` directory.

**Comment by johanneswuerbach** [comment]
Feel free to submit a PR to update the bundled chai. Thank you

**Comment by unwiredbrain** [comment]
Done. Please see PR #474
