### ISSUE TITLE
Testem/PhantomJS fails due to POODLE fix

### ISSUE THREAD

**Issue by estoner** [airportyh/testem#419]
Many HTTPS services have disabled SSLv3 as of yesterday due to the POODLE vulnerability.  PhantomJS defaults to using SSLv3, and Testem doesn't (to my knowledge) allow the user to pass the necessary command-line arguments to force PhantomJS to TLSv1.  Consequently, any tests that hit correctly-configured HTTPS services will fail.

This is also an issue with PhantomJS, obviously, but if you're using vanilla PhantomJS it's trivial to work around this problem by just adding this argument:
```
--ssl-protocol=[sslv3|sslv2|tlsv1|any] sets the SSL protocol for secure connections (default is SSLv3)
```

See also https://github.com/ariya/phantomjs/issues/12651

**Comment by knownasilya** [comment]
How do you pass the arguments via testem?

**Comment by johanneswuerbach** [comment]
You can specify custom parameters using `phantomjs_args` in your config.
https://github.com/airportyh/testem/pull/560
