### ISSUE TITLE
Browserify is doing weird stuff when called from testem.

### ISSUE THREAD

**Issue by MoOx** [airportyh/testem#431]
Here is a test in `src/components/whatever/index.test.js`

```js
var test = require("tape")

test("this is a test", function(t) {
  t.ok(true, "should be OK")
  t.notOk(false, "should be NOK")
  t.end()
})
```

Here is something that is working

```console
$ browserify src/**/*.test.js | node
TAP version 13
# this is a test
ok 1 should be OK
ok 2 should be NOK

1..2
# tests 2
# pass  2

# ok
```

Here is my testem config

```json
{
  "framework": "tap",
  "src_files": ["src/**/*.test.js"],
  "before_tests": "browserify src/**/*.test.js -o tests.js",
  "serve_files": ["tests.js"]
}
```

Here is what is giving `testem ci`

```console
$ testem ci                         
not ok 1 Error
    ---
        message: >
            Error: Cannot find module '/Users/MoOx/testem-test/src/**/*.test.js' from '/Users/MoOx/testem-test'
                at /Users/MoOx/testem-test/node_modules/browserify/node_modules/resolve/lib/async.js:42:25
                at load (/Users/MoOx/testem-test/node_modules/browserify/node_modules/resolve/lib/async.js:60:43)
                at /Users/MoOx/testem-test/node_modules/browserify/node_modules/resolve/lib/async.js:66:22
                at /Users/MoOx/testem-test/node_modules/browserify/node_modules/resolve/lib/async.js:21:47
                at Object.oncomplete (fs.js:107:15)
            
    ...

1..1
# tests 1
# pass  0
# fail  1
```

The weird thing is `Error: Cannot find module **/*`. Why is this glob not resolved ?

The super weird part is this one:

```console
$ mv src/components/whatever/index.test.js src/test/index.test.js
$ testem ci
ok 1 Chrome 38.0 - should be OK
ok 2 Chrome 38.0 - should be NOK
ok 3 Firefox 33.0 - should be OK
ok 4 Firefox 33.0 - should be NOK
ok 5 Safari 8.0 - should be OK
ok 6 Safari 8.0 - should be NOK
ok 7 Opera 25.0 - should be OK
ok 8 Opera 25.0 - should be NOK

1..8
# tests 8
# pass  8
# fail  0

# ok
```

Another weird thing is that if I move `src/test/index.test.js` into `src/index.test.js`, this is giving me the same previous error.
It's like `**/*` is acting like a strict `*/*`. But not from my terminal (zsh).

**Comment by jasonkarns** [comment]
It's _kind of_ a testem issue. It's because the commands are run in subshells and the user's environment isn't carried over (see #437). For instance, the same situation applies for bash users if `globstar` is set (which makes bash respect `**`, but the testem-spawned subshell does not have `globstart` set).

**Comment by paytonrules** [comment]
I just wanted to mention that I've been looking for something like @MoOx 's find trick up there for a month. Very neat.

**Comment by jasonkarns** [comment]
According to the gnu bash manual, https://www.gnu.org/software/bash/manual/html_node/Command-Execution-Environment.html, shell options (like `globstar`) are not copied to child processes. I think this should probably be closed.

**Comment by johanneswuerbach** [comment]
Thanks, for the update. Closing!
