### ISSUE TITLE
0.6.23 bundles too much in express

### ISSUE THREAD

**Issue by yarrow** [airportyh/testem#435]
0.6.23 has the following modules in express/node_modules which are not in 0.6.22: basic-auth, crc, depd, escape-html, media-typer, merge-descriptors, parseurl, proxy-addr, and vary. This causes a screenful of error messages of the form

    npm WARN unmet dependency .../testem/node_modules/express/node_modules/connect/node_modules/cookie-parser requires cookie@'0.1.2' but will load
    npm WARN unmet dependency .../testem/node_modules/express/node_modules/cookie,
    npm WARN unmet dependency which is version 0.0.5

**Comment by newtriks** [comment]
:+1:

**Comment by airportyh** [comment]
This fixes it https://github.com/airportyh/testem/commit/13951c27dde11dbff3be718fe7641c73c28bbfca

@MoOx yes, I need and would love some help. And if you need help helping, please ask.
