### ISSUE TITLE
How can I get a full stacktrace/message output with each failing test?

### ISSUE THREAD

**Issue by toranb** [airportyh/testem#439]
I'm using Testem and my config is simple for now

```js
{
  "framework": "qunit",
  "test_page": "tests/index.html",
  "launch_in_ci": [
    "PhantomJS"
  ],
  "launch_in_dev": [
    "PhantomJS",
    "Chrome"
  ]
}

```

One thing I've noticed is that I don't get the full stacktrace /message output when phantomjs or chrome run my tests. Is this a language dep/test library specific feature? If not -how can I get this stack information w/ each test?

Thanks for such an amazing project!

**Comment by johanneswuerbach** [comment]
Hi, is this still an issue? Are you trying to receive stracktraces in ci or dev mode? I dev they should be printed to your local console as usual.

**Comment by toranb** [comment]
Thanks for the reply!

If I'm using the broken phantomjs browser (headless) in dev I don't get a stacktrace. Do you know how to configure either testem/and or phantom to dump the stack to the console so I can see it?

Most of my pairing is pure terminal driven *(tmux and vim)* so only getting these in chrome doesn't help sadly.

Thanks for maintaining this great project!

**Comment by johanneswuerbach** [comment]
I'm usually debugging phantomjs using the remote debugger.
```
$ ./node_modules/.bin/testem dev
$ phantomjs --remote-debugger-port=7777 --remote-debugger-autorun=true ./node_modules/testem/assets/assets/phantom.js http://localhost:7357/
```
Which allows to open `http://localhost:7777` and have an inspector, but I guess this won't really help in your case.
Atm stacktraces aren't serialized and transmitted to the testem server, but it might be possible to implement this. A starting point could be here: https://github.com/airportyh/testem/blob/2e59012a595d20529538e7b7b6957511d2094e28/public/testem/testem_client.js#L169

**Comment by toranb** [comment]
Great feedback! When I get some bandwidth I'll take your start and look at what a PR might turn into!
