### ISSUE TITLE
Testem not finding any launchers with Chrome and Firefox

### ISSUE THREAD

**Issue by duncan-bayne** [airportyh/testem#449]
If I run `testem launchers` on my system, I see:

```
info Seeking for config file... 
Have 0 launchers available; auto-launch info displayed on the right.

Launcher      Type          CI  Dev
------------  ------------  --  ---
```

I have the following browsers installed:

* Mozilla Firefox 34.0.5 in `/usr/local/bin/firefox`
* Chromium 39.0.2171.95 in `/usr/local/bin/chrome` (with ChromeDriver 2.10 in `/usr/local/bin/chromedriver`)

My Testem and Node versions are:

* Node v0.10.33
* Testem 0.6.24

My OS version is:

* FreeBSD 10.1-RELEASE #0 r274401: Tue Nov 11 21:02:49 UTC 2014  root@releng1.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64

**Comment by amercier** [comment]
Same with Chrome and Firefox installed in `~/Applications` instead of `/Applications`.

**Comment by duncan-bayne** [comment]
What's your $PATH?  It sounds like Testem is simply disregarding $PATH and looking where it thinks binaries might be.

**Comment by duncan-bayne** [comment]
Having had a look at 
https://github.com/airportyh/testem/blob/master/lib/browser_launcher.js I'm not surprised by this behaviour.

![nope into the sun](http://i1302.photobucket.com/albums/ag137/nelsonmonty/nope_zpsbcc14df0.gif)

**Comment by amercier** [comment]
Looking at the `$PATH` wouldn't work either on MacOS.

**Comment by einoodle** [comment]
I'm running on Mac, and i works with testem version mentioned and OS X Yosemite. To be specific, it launches Safari and Chrome.

**Comment by amercier** [comment]
I assume you installed these browsers in `/Application`. It does not work if you install them in `~/Application` (= `/Users/<you>/Applications`).

**Comment by johanneswuerbach** [comment]
@amercier Feel free to send a PR adding `~/Application` to testems search paths.
@duncan-bayne `/usr/local/bin/` should be listed in $PATH as testem only tries to execute `firefox` without any path? Testem is using `google-chrome` to lunch Chrome, is `chrome` the default binary name on BSD?

**Comment by jasonkarns** [comment]
I agree that `~/Applications` should be included in testem's paths. That's the default location into which brew-cask installed apps are symlinked.
