### ISSUE TITLE
Tag repo on NPM release?

### ISSUE THREAD

**Issue by rwjblue** [airportyh/testem#454]
ember-cli is updating from v0.6.26 to v0.6.28 in https://github.com/ember-cli/ember-cli/pull/2941, tracking down the actual sha's that comprise each version is much more difficult than using tags.

In the case of this update without tags, the compare view is https://github.com/airportyh/testem/compare/3517b651e6c9a965451a376ed421a4015953c27a...e606e9124157f882257786d346fbaee8ee8f7bad, but with tags it would have been much easier to review at https://github.com/airportyh/testem/compare/v0.6.26...v0.6.28.

Feel free to close if you'd prefer to not tag. I just figured I'd mention that it is very helpful to some folks...

**Comment by airportyh** [comment]
Done. I had forgotten to `git push --tags`.
