### ISSUE TITLE
Running testem with node --debug  throw new Error('can\'t set raw mode on non-tty');

### ISSUE THREAD

**Issue by QuantumInformation** [airportyh/testem#462]
I'm trying to debug a qunit ember integration test. But am coming up against a deprecation in testem

I'm running like so:

```/usr/local/bin/node --debug-brk=59771 --nolazy --harmony /Users/me/github/app/node_modules/ember-cli/bin/ember test -s```

The output:

```
debugger listening on port 59771
version: 0.1.7
Could not find watchman, falling back to NodeWatcher for file system events
BuildingBuilding.Building..Building...Building...

Build successful - 1853ms.
c[?25l[8;NaNrtty.setRawMode: Use `process.stdin.setRawMode()` instead.

tty.js:37
    throw new Error('can\'t set raw mode on non-tty');
          ^
Error: can't set raw mode on non-tty
    at tty.js:37:11
    at deprecated (util.js:77:15)
    at module.exports.View.extend.cleanup (/Users/me/github/app/node_modules/app/node_modules/testem/lib/dev/ui/appview.js:260:5)
```

**Comment by johanneswuerbach** [comment]
Thanks for the report, which node version are you using?

**Comment by QuantumInformation** [comment]
Hey Johannes!

Its node v0.10.33

**Comment by QuantumInformation** [comment]
Looks like its how the way webstorm works, thats how I'm trying to attach to the debug process..

https://youtrack.jetbrains.com/issue/WEB-1933

**Comment by johanneswuerbach** [comment]
I was not able to reproduce your issue, but removed the deprecated call. Could you test whether https://github.com/airportyh/testem/pull/464 fixes your issue?

You can test this branch using
```
git clone https://github.com/johanneswuerbach/testem.git
cd testem
git checkout removed-deprecated
npm install
npm link
cd your_app/node_modules/ember-cli
npm link testem
```
revert:
```
cd your_app/node_modules/ember-cli
npm unlink testem
cd testem_folder
npm unlink
```

**Comment by johanneswuerbach** [comment]
A fix is release now.
