### ISSUE TITLE
How to gather test results if the browser exits before test case's execution in CI mode with a HTML test page?

### ISSUE THREAD

**Issue by kongchen** [airportyh/testem#469]
As title, if I put test cases in `setTimeout(fn, delay)` and make the `delay` a bit longer (e.g 5000ms), the browser process will exit before the `fn` is executed.

I think code express more precious and clear than words:
The **test.html**:
```html
<html>
  <script src="unit/lib/qunit-1.11.0.js"></script>
  <script src="/testem.js"></script>
  <body>
    <script>
      setTimeout(function(){
        QUnit.test( "hello test", function( assert ) {
          assert.ok( 1 == "1", "Passed!" );
        });
        }, 5000);
    </script>
  </body>
</html>
```

Run the test page using *testem*, and you see the result is wrong:
```
$ testem ci  -l chrome -t test.html                                                                                                      
1..0
# tests 0
# pass  0
# fail  0

# ok
```

If I comment the setTimeout method in **test.html**:
```html
<html>
  <script src="unit/lib/qunit-1.11.0.js"></script>
  <script src="/testem.js"></script>
  <body>
    <script>
      //setTimeout(function(){
        QUnit.test( "hello test", function( assert ) {
          assert.ok( 1 == "1", "Passed!" );
        });
//        }, 5000);
    </script>
  </body>
</html>
```

I'll get correct test result:
```
$ testem ci  -l chrome -t test.html                                                                                                      
ok 1 Chrome 40.0 - hello test

1..1
# tests 1
# pass  1
# fail  0

# ok
```

I looked into the source code and found the `onAllTestResults` in *browser_test_runner.js* is called before my tests run.

Add a timeout to wait the tests is a workaround, it resolved the problem:
```js
onAllTestResults: function(results){
    var self = this
    setTimeout(function() {
      self.launcher.kill(null, function(){
        self.finish()
      })
    }, 6000);
  },
```
But it's a bit ugly: you can see I wait for 6s, but actually the test case is finished at 5.0001s and it will still wait one more seconds.

Is there any other ideas for this?

**Comment by johanneswuerbach** [comment]
When you need to define your tests async, you can set `QUnit.config.autostart` to `false` and execute `QUnit.start` manually after all tests are loaded. http://api.qunitjs.com/QUnit.config/

**Comment by kongchen** [comment]
Thanks for the info, it helps.
