### ISSUE TITLE
Allow for proxies at the route level path '/'

### ISSUE THREAD

**Issue by jonathanKingston** [airportyh/testem#496]
To allow for RESTful API's Testem should support proxies that start at the route level.

For example the following paths:
```
POST /users
PUT /users/1
GET /posts
```

Currently by setting a the '/' in the proxies testem.json config the test response in browsers return the server response at '/' rather than the testing interface.

```
{
  "framework": "qunit",
  "test_page": "tests/index.html",
  "launch_in_ci": [
    "PhantomJS"
  ],
  "launch_in_dev": [
    "PhantomJS",
    "Chrome"
  ],
  "proxies": {
    "/": {
      "target": "http://localhost:8000"
    }
  }
}
```

This means that for the browser interface to return that is being tested that testem uses content negotiation to look at headers like content type. For example behaviour Ember CLI applications support this behaviour.

Original ticket: https://github.com/ember-cli/ember-cli/issues/3227#issuecomment-73463386

**Comment by johanneswuerbach** [comment]
I would definitely accept a PR for this, but won't have time to implement this myself in the near future. If anybody wants to tackle this, all express / proxy configuration is done here: https://github.com/airportyh/testem/blob/master/lib/server/index.js#L124

**Comment by jonathanKingston** [comment]
@johanneswuerbach I started on this in: https://github.com/jonathanKingston/testem/commit/9a296c5ddf7f6a98e557a769b79bc4d82d0559aa

Which works for the cases I wanted however tests are failing because I assume they are not sending content-type headers.

Would you prefer the content negotiation to be part of the config or globally on like this is?

Will tackle the tests tomorrow and any updates of docs.

**Comment by johanneswuerbach** [comment]
Thanks @jonathanKingston, this looks great. I think we should add an option to enable / disable this as I think there are definitely cases, where you want to serve local json files.

What do you think about `onlyContentTypes: ['xml', 'json']` as a setting inside a proxy object?

**Comment by jonathanKingston** [comment]
@johanneswuerbach should be ready to merge.
As for serving JSON assets locally, I was thinking long term the test code, its assets  and the HTML should be on a separate port to the application anyway; this would vastly simplify this proxy code and peoples use.
