### ISSUE TITLE
Secure cookies which are returned from HTTPS proxy can't be used by the browser, since testem internal server is HTTP

### ISSUE THREAD

**Issue by timurua** [airportyh/testem#497]
Testem version: 0.6.39
Node version: 0.10.32

Testem.json

```json
{
  "framework": "qunit",
  "routes": {
    "/index.html": "../resources/static/index.html",
    "/scripts": "../resources/static/scripts",
    "/styles": "../resources/static/styles",
    "/tests": "../resources/static/tests",
    "/images": "../resources/static/images"
  },
  "proxies": {
    "/api": {
        "target": "https://host:8443",
        "secure": false
    }
  },
  "test_page": "index.html?test",
  "launch_in_dev": ["Safari"],
  "launch_in_ci": ["PhantomJS"]
}
```
Request
```http
POST /api/login HTTP/1.1
...
```

Response
```http
HTTP/1.1 200 OK
...
Set-Cookie: jsessionid=3e3063c377f93d5fc7291325378363d3e7f5;Secure;HTTPOnly
```

Because testem is working with HTTP and not HTTPS, the secure cookie can not be used by the browser for subsequent requests. This behavior brakes my login flow - the user is not able to log in.

**Comment by timurua** [comment]
I unfortunately can't modify the server. :-(((( . This is so disappointing.

**Comment by timurua** [comment]
Wow! Awesome! That was quick. Thanks a lot! Looking forward to test it.

**Comment by johanneswuerbach** [comment]
You can test this now by installing the latest testem pre-release `npm install -g testem@0.7.0-0` or locally using `npm install testem@0.7.0-0 --save`.
