### ISSUE TITLE
Uncaught ReferenceError: io is not defined

### ISSUE THREAD

**Issue by Denk** [airportyh/testem#500]
We've been using testem for a while now and since one of the later versions, we're encountering an error.

Situation: We're using grunt-testem, which uses testem-multi. In their package.json it uses testem version ^0.6.18.

This installs the latest testem version 0.6.39.

We're running the following commands:

```
istanbul instrument --output _test/instrumented src/classes
testem
```

Testem config:
```
module.exports = {
	all: {
        files : {
          '_test/tmp/result.tap': ['_SpecRunner.html']
        }
	},
	options : {
        output: {
          coverage: '_test/tmp/coverage/from_browsers/'
        },
        routes: {
          "/instrumented": "_test/instrumented"
        },
		launch_in_ci : [
			'chrome'
		]
	}
};
```

_SpecRunner is a test page which includes jasmine

On the test page, we now get the following error:
```
Uncaught ReferenceError: io is not defined
```

Traced it back to the following line:
```javascript
socket = io.connect({ reconnectionDelayMax: 1000 })
```

When I change the version of testem to 0.6.24 (so not ^0.6.18, which installs the latest version 0.6.39), I don't have any problems and my tests pass again.

**Comment by johanneswuerbach** [comment]
[testem-multi is patching](https://github.com/sideroad/testem-multi/blob/master/lib/coverage_middleware.js#L12) some internal testem functions, which broke your project.

What is your use-case for using https://github.com/sideroad/testem-multi? Maybe testem could provide some features itself.

**Comment by Denk** [comment]
@johanneswuerbach thx for the reply and quick fix!

Well, we first used grunt+grunt-testem and now we're switching to gulp+gulp-testem and both use testem-multi. I believe the only reason why was because it sets up the server for us and we can focus on our tests.

I'll take a look at implementing testem directly.

**Comment by johanneswuerbach** [comment]
Thanks for the update. I see both projects provide code coverage support, which testem does not. Maybe it's time to release an official plugin for that.
