### ISSUE TITLE
xunit reporter does not escape xml properly

### ISSUE THREAD

**Issue by Twinkletoes** [airportyh/testem#511]
If an error message contains a double quote, the output xml is not valid.

**Comment by Twinkletoes** [comment]
Can we get a release with this PR so that ember-cli (downstream) is fixed?

**Comment by johanneswuerbach** [comment]
Sure, I'll cut a release early tomorrow (CET).

**Comment by johanneswuerbach** [comment]
0.7.2 includes this fix.
