### ISSUE TITLE
after ctrl-c cursor is not restored to the shell

### ISSUE THREAD

**Issue by stefanpenner** [airportyh/testem#513]
node `0.10.35` `1.2.0` and `0.12.x`
os: `OS X 10.10.2`
testem: `0.7.1`

steps to reproduce:

1. run testem
2. `<ctrl>-c` to exit

expected result:

* return to the invoking shell, and the cursor is restored

actual result

* returned to the invoking shell, but the cursor is gone.

**Comment by johanneswuerbach** [comment]
I never worked with painting UIs in a terminal. @airportyh ideas?
