### ISSUE TITLE
testem trigger a security issue on windows 8.1 + IE

### ISSUE THREAD

**Issue by MoOx** [airportyh/testem#522]
Any idea about that ?

![screen shot 2015-03-26 at 09 01 33](https://cloud.githubusercontent.com/assets/157534/6842325/c0f78062-d396-11e4-967c-26bb42dea9d9.png)

It seems some tests can run but some others cannot. Not sure why. Any clue ?

**Comment by johanneswuerbach** [comment]
I have no idea, the only reason I found is when you are using links with embedded login information.

http://stackoverflow.com/questions/3079901/ie8-throwing-a-security-error-with-mootools

Do you?

**Comment by MoOx** [comment]
OK NEVER USE A STUPID URL LIKE HTTP//@TODO in your tests.
(security issue because of user:pwd@domain..)
Sorry :)

**Comment by johanneswuerbach** [comment]
Yeah, this was easy solve :smile:
