### ISSUE TITLE
https support of testem server

### ISSUE THREAD

**Issue by hideyuki** [airportyh/testem#523]
I want to startup the testem server on https://localhost:7357 for WebAudioAPI testing.

I found the server code and realize I need set the parameters "key" and "cert" if use https server.
https://github.com/airportyh/testem/blob/master/lib/server/index.js#L59

So I make the testem.json like following and it works on https://localhost:7357.
```
{
  "src_files": [
    "js/**/*.js",
    "spec/**/*.js"
  ],
  "key": "ssl/server.key",
  "cert": "ssl/server.crt"
}
```

But url on testem window is stil http scheme:
```
TEST'EM 'SCRIPTS!                                                                                                                                                                                                
Open the URL below in a browser to connect.                                                                                                                                                                      
http://localhost:7357/   
```

Is this the best way to start up the testem server with https?
If yes, I will make a Pull-Request to fix this bug.

**Comment by johanneswuerbach** [comment]
Yes, this should work. Did you try whether you can access it via `https://localhost:7357/`? Maybe the output is just wrong.

**Comment by hideyuki** [comment]
>Did you try whether you can access it via https://localhost:7357/?
Yes.
I could see the runner page on https://localhost:7357 and the testem can communicate with runner page.

>The url has http hardcoded :cry:
I will send PR soon!
