### ISSUE TITLE
Doesn't work when custom test page is the active tab

### ISSUE THREAD

**Issue by ThomPatterson** [airportyh/testem#526]
I have a small SPA using Backbone, jQuery Mobile and RequireJS.  My grunt tasks include grunt-contrib-jasmine for the initial execution of the unit tests.  The _SpecRunner.html file that creates has the testem.js reference, so I use that as the test_page for testem.  This seems to work, except testem only sees the results from the tests when it is not the active tab.  I discovered this by accident when I opened a new tab to investigate the issue.  I've put together a quick video demonstrating the problem.  I've recreated this problem on OS X and Windows 8.1 with every browser I've tried (Chrome, Safari, Firefox, IE11).

http://www.youtube.com/watch?v=adhC8v9976M

**Comment by johanneswuerbach** [comment]
Are there any js errors and which testem and node version are you using?

**Comment by ThomPatterson** [comment]
No JS errors, but there is a warning that I get in the spec runner that I don't get while running the app normally.

Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.
jquery-2.0.3.min.js:6

Node v0.12.0
Testem 0.7.6

**Comment by johanneswuerbach** [comment]
Do you use `Synchronous XMLHttpRequest`? Maybe this is effecting testem.

**Comment by ThomPatterson** [comment]
The app uses Backbone to fetch the data, so it is asynchronous.  The unit test uses jasmine-jquery to load an HTML fixture, I wonder if that is synchronous?

**Comment by johanneswuerbach** [comment]
Yes it looks like: https://github.com/velesin/jasmine-jquery/blob/cd112dd7653a2c10a0c7a5f2ad2e87289a1d70ba/lib/jasmine-jquery.js#L125 I'll try to investigate when I have some time.

**Comment by ThomPatterson** [comment]
I refactored by project to use Browserify instead of RequireJS.  CJS instead of AMD.  Although the previously mentioned "Synchronous XMLHttpRequest on the main thread is deprecated..." warning is still present, Test'em now works in the active tab in all browsers.  So the issue may have had something to do with RequireJS or grunt-template-jasmine-requirejs.
