### ISSUE TITLE
Reduce stack trace option

### ISSUE THREAD

**Issue by newtriks** [airportyh/testem#539]
Currently I am finding using Jasmine2 if a test fails I am getting excessive stack traces resulting in pages of scrolling simply to find the failing test. Is there any way to configure the stack traces at all?

**Comment by johanneswuerbach** [comment]
No, currently there is none.

**Comment by newtriks** [comment]
@johanneswuerbach ok thanks. Editing https://github.com/airportyh/testem/blob/master/public/testem/jasmine2_adapter.js is the easiest option to achieve what I want, however, if I create a new custom adaptor based on this file Jasmine seems to struggle finding window. Any tips?

**Comment by johanneswuerbach** [comment]
I never worked with jasmine 2, could you provide a repo to reproduce this? There are a bunch of files required for jasmine2, maybe you need to load `jasmine2-boot.js` manually? https://github.com/airportyh/testem/search?utf8=%E2%9C%93&q=jasmine2

**Comment by newtriks** [comment]
Good point, I shall have a tinker. Thanks
