### ISSUE TITLE
Page reloads without finishing tests

### ISSUE THREAD

**Issue by luketheobscure** [airportyh/testem#547]
When running the testem server and accessing the runner in the browser, the page reloads over and over again, without ever finishing the tests.

It seems to be due to this method, which I think is fired in response to a socket.io method:

```
function startTests(){
  socket.disconnect()
  parent.window.location.reload()
}
```

I'm happy to provide more information, and would love some debugging advice if you think it's a bug in my setup. If it helps, this is a test suite for a very (*very*) large Ember.js app, using QUnit as the testing framework.

**Comment by wilsonohyeah** [comment]
I have the same setup and have experienced this issue as well. I ended up just using `npm test` to run things from the console but testing in the browser would be really nice for debugging purposes.

**Comment by johanneswuerbach** [comment]
I'll take a look. Just to double check, which os / node / testem version are you running?

**Comment by luketheobscure** [comment]
Node: v0.12.2
NPM: v2.1.6
Testem: v0.8.2
OSX 10.10.2

Thanks!

**Comment by johanneswuerbach** [comment]
This should be fixed by https://github.com/airportyh/testem/issues/550. Could you add `"disable_watching": true` to your `testem.json`?

**Comment by johanneswuerbach** [comment]
ember-cli PR https://github.com/ember-cli/ember-cli/pull/3962

**Comment by luketheobscure** [comment]
That fixed it. You're awesome.
