### ISSUE TITLE
LastPass chrome addon pops up a window in testem spawned chrome

### ISSUE THREAD

**Issue by gnarf** [airportyh/testem#549]
This window popping up causes the tests to lose focus, which causes lots of tests to timeout/fail because the window doesn't have focus.

I have tried to figure out how to completely remove lastpass on my mac to no avail, however I was wondering if there might be some way to disable loading that addon in the custom profile you make for chrome.

**Comment by johanneswuerbach** [comment]
Sadly not, LastPass should definitely no auto install itself into new profiles.

**Comment by gnarf** [comment]
I still have no idea how to remove this extension completely from my system - I've looked around a lot...

I found a bunch of copies of the extension and removed them: 

```bash
sudo find / -name hdokiejnpimakedhajhdlcegeplioahd
```

But every time I start a new testem chrome, the lastpass extension still worms it way back into my fresh profile :( --- Any thoughts that might help here by any chance?

**Comment by johanneswuerbach** [comment]
Sorry, no idea, did you contact the lastpass support already?

**Comment by gnarf** [comment]
I haven't had any luck finding a lastpass support either -- just a help center with no "did this not help, email us" links anywhere...

I guess I'll try twitter: https://twitter.com/gnarf/status/608357334096744448

**Comment by Protonk** [comment]
Looks to me like adding `--disable-extensions` to the launcher will stop this from happening (for Lastpass as well as any other). Will that break any behavior testem relies on, @johanneswuerbach?

**Comment by johanneswuerbach** [comment]
No, but it would further change the browser and might produce false-positives. I'll look into providing this as an option, so you could enable this if required.

**Comment by Protonk** [comment]
I didn't know about this project until today, so take anything I say with the requisite amount of salt. ;)

But wouldn't disabling extensions mean that less local state leaks into the window for testing? i.e. If I had extensions that caused tests to fail I should want them to be kept out of the picture.

**Comment by gnarf** [comment]
I feel like you'd want to default to disabled extensions, the odd case
where you're testing in a browser and you want an extension seems like the
flag

**Comment by johanneswuerbach** [comment]
Yes, but your users won't have those flags set, so each non-default flag increases the difference to your users.

We already create every browser with a new profile to prevent your local settings leaking into the runner:
https://github.com/airportyh/testem/blob/master/lib/browser_launcher.js#L97

Sadly LastPass is silently-installing their extensions into every new profile like those old IE toolbars :cry:

**Comment by gnarf** [comment]
I see what you mean... I really hope lastpass will step up and read this
issue.

**Comment by karbassi** [comment]
Check your `external_extensions.json` file. It's in different locations on different OSes.

**Comment by gnarf** [comment]
Not listed there...  :frowning:

**Comment by john-kurkowski** [comment]
I fixed this by uninstalling LastPass's [recommended LastPass Complete installer](https://lastpass.com/misc_download2.php) from my whole system. It apparently installs LastPass into all current browsers and future browsers. From [this exchange](https://twitter.com/LastPassHelp/status/660153645078437888), I learned I could install the Chrome extension individually [from the Chrome store](https://chrome.google.com/webstore/detail/lastpass-free-password-ma/hdokiejnpimakedhajhdlcegeplioahd). Now, no more LastPass popup when running Testem!

**Comment by tandrewnichols** [comment]
For anyone else who finds this, the last pass download page no longer has the Uninstaller separately available for download. I had to locate the original download of lastpass, which included both an installer and an uninstaller. A bit tedious, but LastPass no longer tries to jump on my testem window.
