### ISSUE TITLE
launch_in_ci not being respected

### ISSUE THREAD

**Issue by mudetroit** [airportyh/testem#553]
I am trying to setup testem ci to run inside of travis ci. I only want to phantomjs to run in the ci environment so I setup my .testem.json as follows:
```json
{
	"framework": "jasmine",
	"launch_in_dev": [
		"Chrome",
		"Firefox",
		"Safari"
	],
	"launch_in_ci:": [
		"PhantomJS"
	]
}
``` 

When I check the launchers though I see the following.
```
Launcher      Type          CI  Dev
------------  ------------  --  ---
Chrome        browser       ✔    ✔
Firefox       browser       ✔    ✔
Safari        browser       ✔    ✔
PhantomJS     browser       ✔
```

I have checked different casing and that doesn't seem to be the issue. Am I missing something basic here or is this a real problem?

**Comment by johanneswuerbach** [comment]
It should be `testem.json` not `. testem.json` :smile:

**Comment by mudetroit** [comment]
See that would be the simple thing I was talking about. Thanks
