### ISSUE TITLE
native extension (BufferUtil) in WS is problematic.

### ISSUE THREAD

**Issue by stefanpenner** [airportyh/testem#554]
problem:

* native extension is slow to compile
* on various platforms / setups, the needing toolchain is missing or broken.
  * although the failure doesn't affect the outcome, the failure output confuses new users
* as testem is for dev, the extra "performance" the c-extension provides is of very little benefit.

Proposed solution:

* fork of socket.io > engine.io > ws -> bufferutil that doesn't have the native dependency.

thoughts?

**Comment by johanneswuerbach** [comment]
bufferutil was recently made an optional dependency https://github.com/websockets/ws/releases/tag/0.7.1. Would this help?

ws 0.7.1 is already in socket.io, just not released yet. Maybe @rauchg knows more about that?

**Comment by rauchg** [comment]
it shall ship in `1.4.0` due asap

**Comment by stefanpenner** [comment]
@johanneswuerbach given the timeline of socket.io releasing another version (waiting since may 1) https://github.com/Automattic/socket.io/issues/2107 Would you be open to accepting an interim fork of socket.io that doesn't have these issues?

This should be considered an interim solution

**Comment by johanneswuerbach** [comment]
Sure, sadly we would have to maintain multiple modules to fix the problematic ws version https://github.com/Automattic/socket.io/blob/master/package.json#L24-L27

@rauchg was mentioning somewhere that the current master has an issue somewhere, but I don't find that comment.

**Comment by stefanpenner** [comment]
@johanneswuerbach i was thinking of just forking the tree of the version we currently use, fixing everything and then bundling the dependencies.

**Comment by johanneswuerbach** [comment]
Right, sounds like a better plan.

**Comment by stefanpenner** [comment]
@johanneswuerbach i'll plan to work on this tomorrow.

**Comment by johanneswuerbach** [comment]
Wait, did we really missed that? :scream: https://github.com/airportyh/testem/pull/602 

https://github.com/Automattic/socket.io/releases/tag/1.3.6

**Comment by rauchg** [comment]
I should have notified you! Sorry about that. `1.3.6` fixes all the build issues 🎉

**Comment by stefanpenner** [comment]
yay
