### ISSUE TITLE
Tests not running on phantom and hanging

### ISSUE THREAD

**Issue by msecret** [airportyh/testem#555]
I'm running the command `$ testem ci -l phantomjs -d` on Fedora Linux. My tests are all working on chrome and firefox. On phantomjs, they're hanging and not running at all. I've also tried to run them on travis with no luck, same result.

```
$ node --version
> v0.11.16
```
```
$ phantomjs --version
> 1.9.8
```
```
$ testem --version
0.7.7
```
```
$ cat testem.log 
info Test'em starting... 
info Seeking for config file... 
info Starting ci 
info Starting server 
info Process PhantomJS already killed. 
info spawning: /home/msecret/.nvm/v0.11.16/lib/node_modules/phantomjs/lib/phantom/bin/phantomjs - ["/home/msecret/.nvm/v0.11.16/lib/node_modules/testem/assets/phantom.js","http://localhost:7357/3038"] 
info New client connected: PhantomJS 1.9 3038 
```

**Comment by johanneswuerbach** [comment]
Hey, could you provide a repo to reproduce this?

**Comment by msecret** [comment]
https://github.com/aronnax/store

**Comment by johanneswuerbach** [comment]
Did you fix anything? I can't reproduce the issue locally and your travis build seems to be passing too https://travis-ci.org/aronnax/store
