### ISSUE TITLE
Some paths are hard-coded to never be watched

### ISSUE THREAD

**Issue by ef4** [airportyh/testem#563]
Fireworm has [default paths that it will not traverse](https://github.com/airportyh/fireworm/blob/88d8130b8acda5b47d61db436941b401e8ba509c/index.js#L23).

But testem [does not expose an option](https://github.com/airportyh/testem/blob/b3efcabb5844193c3adc7c0a331b179dcd55b70e/lib/dev/index.js#L147-L149
) for us to override these paths, as far as I can see. So even if a user sets them explicitly in `watch_files`, they won't work.

There are good reasons to sometimes want to watch a path like `node_modules` -- like when you're actively developing multiple modules that are npm-linked together.

I can make a PR to fix this, but what public API should it have? I think testem's behavior is clearer if it simply sets `skipDirEntryPatterns` to `[]` and lets the user control the patterns via `watch_files/src_files` and `src_files_ignore`.

**Comment by johanneswuerbach** [comment]
Yes, that would make sense. Could you send a PR?
