### ISSUE TITLE
Just launch IE and visit URL?

### ISSUE THREAD

**Issue by sleung-ttc** [airportyh/testem#580]
Is there a way to just launch IE and have it join the room hosted on another server?
I have my test server running on linux, and I want to test IE by using a VM.

**Comment by airportyh** [comment]
Yes. Run testem in dev mode, and then point your browser to the host that's running that server. But in ci mode this is more difficult to do.

**Comment by sleung-ttc** [comment]
For the CI job, I am planning to

1) start the server in the master ( testem server )
2) and having downstream jobs to kick off ci mode in the slaves. ( testem ci --host=master --port=7327 )

Is this somewhat correct setup?

**Comment by airportyh** [comment]
Testem doesn't have a way to support a master/slave configuration right now.
