### ISSUE TITLE
Log lines folded in TAP diagnostics

### ISSUE THREAD

**Issue by avdv** [airportyh/testem#581]
TAP produces output a la:

```
ok 1 PhantomJS 2.0 - Check output
    ---
        Log: >
            first log line
            second log line
            third log line
    ...
```

Due to the usage of the folding style (denoted by the `>` ), the log output gets folded into a single line when read by a TAP consumer (ie. when displayed in Jenkins).

I propose to change that to use the [literal style](http://www.yaml.org/spec/1.2/spec.html#id2760844) (denoted by `|`) to preserve the line breaks.

What do you think? Should I submit a PR?

**Comment by johanneswuerbach** [comment]
Yes, a PR sounds good to me :-)
