### ISSUE TITLE
Test doesn't stop running if 'IE' is added under launch_in_ci mode

### ISSUE THREAD

**Issue by shah95rukh** [airportyh/testem#583]
Everything works fine, all the tests runs appropriately but if I add "IE" to ci mode it opens IE runs all the test, closes it but it doesn't end the test in terminal, I have to ctrl-c to end to test. I have internet explorer 11 installed on my windows 7. If I write 'IE11' instead of "IE", it doesn't even open internet explorer.
This is what it looks like ...

 1..640
 # tests 640
 # pass  550
 # fail  90
 Terminate batch job (Y/N)? Y
 
 support@SUPPORT-PC C:\Users\support\Desktop\newui\personal-archive
 $

Cursor keeps blinking after '#fail 90'. So I have to terminate it with ctrl-c.
This only happens when IE is added in ci list.

**Comment by alexlafroscia** [comment]
I think this might be a problem with the way that Testem tells the browser to quit after the tests have completed.  I've been struggling to get Testem working with BrowserStack for the same reason; while the tests will finish running correctly, Testem seems unable to terminate the command that opened the BrowsersStack connection (or in your case, the the command that opened IE), which in tern prevents Testem from completing by itself.

**Comment by johanneswuerbach** [comment]
This is fixed in `v0.9.1`
