### ISSUE TITLE
[Feature Request] let proxy option allow self-signed certificates for https

### ISSUE THREAD

**Issue by efx** [airportyh/testem#584]
I am running an https server locally that uses self-signed certificates. When I include the following in my testem.json, testem fails to start. 
```json
"proxies":   {
    "/api": {
      "target": "https://localhost:10443"
    }
```
The error: 
```
Error: self signed certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:929:36)
    at TLSSocket.emit (events.js:104:17)
    at TLSSocket._finishInit (_tls_wrap.js:460:8)
```
It would be nice to have this as an option to configure, since my local tests do not need production https credentials.

**Comment by efx** [comment]
My above configuration is incorrect and testem starts fine when I add `"secure": false`
```json
"proxies":   {
    "/api": {
      "secure": false,
      "target": "https://localhost:10443"
    }
```
I think it would be helpful to add some documentation for this, because the above configuration is not especially self-explanatory.  Let me know you would like a PR with some extra verbiage explaining this use case.

**Comment by johanneswuerbach** [comment]
Yes, a PR with some additional details around proxy configuration is more then welcome.
