### ISSUE TITLE
c-extensions introduce hazard for broad adoption

### ISSUE THREAD

**Issue by stefanpenner** [airportyh/testem#588]
offending dependencies

* cross-spawn
* socket.io
* ??

both introduce native extensions, neither of which are currently optional.
This limits testem to machines with a compiler toolchain, and in addition to that a compiler toolchain that is setup correctly.

On windows, this also means the compiled dependencies must be within the 255char path limit, or node-gyp explodes.

re: socket.io if they release, the native-extension becomes optional. I have opened [an issue](https://github.com/Automattic/socket.io/issues/2107)

cross-spawn is another thing, as node < 0.12 has no execSync there is no alternative, other then to always do async execs.

**Comment by jrjohnson** [comment]
Also makes builds *very* slow and seems to ruin caching in CI (travis) and deployment (heroku).

**Comment by stefanpenner** [comment]
> Also makes builds very slow and seems to ruin caching in CI (travis) and deployment (heroku).

:+1:

**Comment by johanneswuerbach** [comment]
Sorry, `0.8.4` with `cross-spawn` should not have been released. `0.8.5` goes back to cross-spawn without native extension.

**Comment by johanneswuerbach** [comment]
Testem doesn't require `spawnSync`, send a PR to https://github.com/IndigoUnited/node-cross-spawn/pull/18 to make the native extension optional.

**Comment by stefanpenner** [comment]
@johanneswuerbach nice

**Comment by stefanpenner** [comment]
@johanneswuerbach socket.io is still the big one, it would be nice if they also just offered socket.io-pure or something...

**Comment by satazor** [comment]
@johanneswuerbach If you are only using the async spawn, you may now use https://github.com/IndigoUnited/node-cross-spawn-async instead

**Comment by johanneswuerbach** [comment]
Closing as testem is using `cross-spawn-async` now (thanks @satazor for making this happen) and the only remaining native extension (socket.io) is already tracked here https://github.com/airportyh/testem/issues/554

**Comment by stefanpenner** [comment]
@johanneswuerbach this isn't isn't yet resolved. We are pending a solution to the socket.io problem.

It sounds like maybe we need to fork it for now... lets see. Unfortunate the following has been idling for ages https://github.com/Automattic/socket.io/issues/2107

**Comment by jrjohnson** [comment]
It's not great form, but could testem just depend on a specific commit from socket.io instead of waiting for a release?

**Comment by stefanpenner** [comment]
@jrjohnson many users cannot rely on GIT deps.
