### ISSUE TITLE
8.5 cut is missing all commits since April

### ISSUE THREAD

**Issue by utricularian** [airportyh/testem#590]
Looks like you have an 8.x branch where you're making tags; but the last two commits on the 8.x branch are the 8.3 and 8.5 cuts. The 8.x branch is missing the commits from all of April, May, and June.

Effectively the 8.5 cut just reverted testem to 8.3

**Comment by johanneswuerbach** [comment]
Hi, I just released the first 0.9 prerelease including all commits after `0.8.3`, sorry for the confusion.

You can use the prerelease by specifying testem `0.9.0-0` in your `package.json` or by using `npm install -g testem@0.9.0-0` to install globally.
