### ISSUE TITLE
BrowserStack Integration

### ISSUE THREAD

**Issue by alexlafroscia** [airportyh/testem#604]
I've been trying for weeks now to get Testem and BrowserStack to play nicely together.  I've tried the configuration included in the repo and it simply seems to not work any longer.

When using the `on_start` hook to try to open the connection, it seems to just hang.  I have my configuration set up like this:

```json
{
  "framework": "qunit",
  "test_page": "tests/index.html?hidepassed=true&nocontainer=true",
  "on_start": {
    "command": "~/.browserstack/BrowserStackLocal XXXXXXXXXXXXXXXXXX",
    "wait_for_text": "Press Ctrl-C to exit"
  },
  "launch_in_ci": [
    "BrowserStackIE9"
  ],
  "launch_in_dev": [
    "PhantomJS"
  ],
  "launchers": {
    "BrowserStackIE9": {
      "command": "browserstack launch -t 360 --attach ie:9.0 <url>",
      "protocol": "browser"
    }
  }
}
```

I am using the `BrowserStackLocal` program because that is what is recommended by BrowserStack these days; the alternative method for opening the connection (`browserstack tunnel localhost:<port>`) is explicitly recommended against by the people at BrowserStack, in favor of the binaries that they provide for the same purpose.

I am able to get around this issue, however, by starting the `BrowserStackLocal` program before running the tests and just issuing a timeout with a hope that it will be long enough to establish the connection.  Evidently it is, because I can get the tests to run in BrowerStack, and the results are reporting quite brilliantly.  However, once the tests finish, it seems that Testem is unable to actually quit the `browserstack` program that started the tests.  Because of this, Testem just hangs after the tests finish, until the BrowserStack timeout expires (which I have configured to be 6 minutes, using the `-t 360` option provided`).

Does Testem just not support BrowerStack anymore? The "bleeding edge" support is from years ago now, so I'm worried that either one program or the other has changed enough since then that it no longer works.

**Comment by johanneswuerbach** [comment]
Lets track this in a separate issue. The BrowserStack support was added by somebody from the community and might be outdated, so this might be a good chance to refresh those docs.

Are all browserstack browsers broken or is it just IE? Could you run testem with `-d` and paste the log her?

**Comment by alexlafroscia** [comment]
I actually closed this because I was able to get it working. It seems like, under some circumstances, Testem will just take a while to close the BrowserStack connection.  The issues I've been having are probably with BrowerStack's service and the browsers either not running the tests correctly, or the connection timing out before the tests finish.

**Comment by johanneswuerbach** [comment]
Thanks for the update, I would be great of you could update the example with your configuration :-)

**Comment by alexlafroscia** [comment]
The only real difference is that I'm using the binary instead of the `browserstack` program to make the connection, but I would be happy to submit a PR with that change!
