### ISSUE TITLE
Suddenly, chrome only works when I'm looking at it.

### ISSUE THREAD

**Issue by tandrewnichols** [airportyh/testem#610]
I recently installed Chrome 44.0.2403.89 on my Mac (Yosemite). Prior to this, running testem against Chrome and Phantom worked fine, but suddenly in this build, the Chrome tests won't run unless the Chrome window is the active Window. Which is super annoying because they seem to be running much slower with this build too. The one notable fix in this build of Chrome is that triggered Chrome windows open in the foreground (before, with both testem and webdriver, they would open in the background). Is this a side-effect of that? Or something else? And can it be fixed in this lib or is it a Chrome problem? (And also, I suppose it's worth asking, am I the only one who's seen this behavior?)

**Comment by johanneswuerbach** [comment]
Could you share a repository to reproduce the issue you are seeing?

Never experience that issue before, but I know that iOS safari is throttling background tabs for some time, so maybe Chrome introduced the technique to safe battery?

**Comment by tandrewnichols** [comment]
I'd have to make a test case - the repo I'm seeing this in now is private.

Seems like it could be related to setTimeout and/or setInterval, which, it appears, get throttled by Chrome when in an inactive tab. http://stackoverflow.com/questions/6032429/chrome-timeouts-interval-suspended-in-background-tabs

Does this lib use one of those? I'm guessing not. My guess is the solution (if this is the problem) will have to be in jasmine (which is what we're using).

**Comment by tandrewnichols** [comment]
Ok, so it appears that Chrome has been throttling for quite a while. There's some really bizarre behavior, however. This is a good test page for seeing the throttling effect. http://jsfiddle.net/simevidas/gHZSW/. What's supposed to happen is that when a particular tab is not the active tab _in that window_, timeouts and intervals are triggered at most once per second. You can see that in effect if you open that link in a new tab and then go to another tab and come back. If you open that tab in a new window (or if you tab away from Chrome completely), the background task keeps working normally. It's only when that tab is inactive but it's window is active that it gets throttled. So I would've expected that the window triggered by testem would work in the background since it _is_ the active tab in that window. But it doesn't. Is that possibly related to how Chrome is launched from testem??? I've fiddled with the flags on the launcher, but it doesn't seem to change anything. Anyone, the point is, it seems like it _should_ work even with background throttling because the throttling is per window, not per tab.

**Comment by tandrewnichols** [comment]
Update: this must be based on the version of Chrome installed. I actually see this go away and come back occasionally as I upgrade Chrome. Unfortunate, but probably not anything this library can (or should) address. At the moment, the tests run fine the first time, but when _restarting_, they freeze until I switch over to look at them. ¯\_(ツ)_/¯

**Comment by johanneswuerbach** [comment]
Thanks for updating this :-) :+1:
