### ISSUE TITLE
No stderr in "before_tests" 

### ISSUE THREAD

**Issue by lwhorton** [airportyh/testem#627]
I'm not sure if this is a browserify issues or a testem issue. If I have a `before_tests` that runs a browserify bundle, and that bundle fails (due to syntax error, for example) - the testem console launches and reports "0/0 no tests run". I would expect the process to exit or at least log stderr to the terminal window. Is there a configuration where I can detect these pipeline preprocessor errors in the `before_tests` block?

```json
{
    "framework": "mocha"
    , "src_files": [
         "./web/**/*.js"
    ]
    , "serve_files": ["./specs.js"]
    , "before_tests": "make build-specs"
    , "on_exit": "rm ./specs.js"
    , "launch_in_dev": ["Chrome"]
    , "port": 9001
    , "fail_on_zero_tests": true
}
```

**Comment by johanneswuerbach** [comment]
Is `make build-specs` returning a non-zero return code?

**Comment by aft-luke** [comment]
Running the browserify command manually and then checking `echo $?` does indeed provide a `1`. I'm not super familiar with `make`, but I would assume that it just forwards the returned result?

**Comment by johanneswuerbach** [comment]
Depends on your `Makefile` ;-) what happens when you run `make build-specs` and `echo $?`?

**Comment by aft-luke** [comment]
```bash
Makefile:2: recipe for target 'build-specs' failed
make: *** [build-specs] Error 1
$: echo $?
2
```
