### ISSUE TITLE
WebDriver example

### ISSUE THREAD

**Issue by markelog** [airportyh/testem#629]
Is there way to use webdriver with testem? If it is, could create an example?

With the karma [launcher](https://github.com/karma-runner/karma-webdriver-launcher) is pretty easy, but i didn't found a clear way to do this with testem.

Also, browserstack example requires you to download a binary, sauce example more straightforward, but it is still unclear how you could integrate this in CI run.

**Comment by airportyh** [comment]
The straightforward way would be to write code to interact with WebDriver, and then set up a [launcher](https://github.com/airportyh/testem#launchers) to launcher that process.

**Comment by markelog** [comment]
I was asking you to provide such example, cause i don't know and wouldn't want to spend lots of time to found out, but just start using it.

If you not interested to be user-friendly that is fine too i guess.

**Comment by searls** [comment]
@markelog, Toby doesn't benefit financially from his time spent working on testem. As a fellow maintainer of developer tools that strive to have great ergonomics for developers, our attempt to serve others in the development community is often confused in issues like this one with _customer service_. 

The request you made is far outside the typical use for Testem (what you need is served by a dozen or more other modules), so your request is on its face a lot to ask of a stranger on the Internet.

@airportyh doesn't owe you free labor. It's possible an adapter and launcher could be created and integrated into Testem, perhaps you should consider reading up on how to implement and sharing either with the public as a pull request. Even if you do (and to be honest, when I see passive aggressive replies like yours, I assume they're not interested in putting in the time to give anything back) implement this feature for Testem, you'll probably be long gone when bugs are found or when dependencies break, and Toby will be left on the hook to maintain the feature—a feature he doesn't need himself.

Entitled requests like this one are one way in which open source maintainers usually burn out: they're pressured into adding or accepting features to projects they freely publish in a spirit of collaboration. Over time, their labor of love becomes saddled with more and more code they neither understand nor need. Eventually they grow to loathe spending time on their projects, as each additional edge case dramatically slows down the ability to change, prune, and grow the project over time.

**Comment by markelog** [comment]
I was merely asking about more documentation, there wasn't my intent to be passive aggressive, i wasn't expecting to get "free labor", i'm not sure if that term even applies to oss project, if there is a request and you don't like it, its fine, no big deal. I really meant it.

If you want to do it - do it, if not - don't, denying issue ticket for more documentation, because you don't want to spend time on it and by doing so be less user friendly is just a consequence of that decision.

**Comment by airportyh** [comment]
I misread the request and didn't realize this was a request for an example. I was just trying to point @markelog in the right direction. A PR is welcome. I won't reopen this though because I don't want to add to the already big list of issues.
