### ISSUE TITLE
deprecate 0.8.4 and 0.8.5 on npm registry

### ISSUE THREAD

**Issue by jasonkarns** [airportyh/testem#647]
I did an `npm i testem@latest` which respected my package.json version spec (`^0.8.2`) and thus installed 0.8.5. As noted [here](https://github.com/airportyh/testem/releases/tag/v0.9.0-0), 0.8.4 and 0.8.5 are bad releases, correct?

Could they be deprecated on the registry? I'm assuming (I don't know if this is true) that `npm i testem@latest` would only install the latest non-deprecated package.

https://docs.npmjs.com/cli/deprecate

**Comment by johanneswuerbach** [comment]
Sorry for the late reply, only `0.8.4` was broken and `0.8.5` should work fine so using `^0.8.2` is fine.

**Comment by jasonkarns** [comment]
Ah, I assumed it was a bad version when testem was throwing errors for me. But now I can't seem to reproduce them.

thanks!

**Comment by jasonkarns** [comment]
though I'd still recommend deprecating 0.8.4 so people will get a warning if they attempt to install it.

**Comment by johanneswuerbach** [comment]
Sure, `0.8.4` is deprecated now.
